export const OBJ_FETCH_BENEFICIARIES = {
  SUCCESS: "FETCH_BENEFICIARIES",
};

export const OBJ_ADD_EDIT_BENEFICIARY = {
  SUCCESS: "ADD_EDIT_BENEFICIARY",
};

export const OBJ_DELETE_BENEFICIARY = {
  SUCCESS: "DELETE_BENEFICIARY",
};

export const TOGGLE_POPUP = "TOGGLE_POPUP";

export const SHOW_TOAST = "SHOW_TOAST";
